Sanitizing Documentation
Cox-Automotive/terraform-provider-alks pull request #173
Opened 2022-06-20 18:15 UTC by jared-bloomer

# Description

Sanitizing Documentation to remove references to Cox Auto resources

Rally # (issue / story / spike)
N/A

## Type of change

_Please remove options that are not relevant._
- [X] Documentation

# How has this been tested?

## Steps:
N/A

# Checklist / To Do:

Merge PR

2022-06-20 19:12 UTC, twang817 approved these changes

2022-06-20 19:13 UTC, twang817 requested changes

2022-06-20 19:13 UTC, twang817 commented on docs/index.md
> +For questions, please reach out to the [ALKS team](https://github.com/orgs/Cox-Automotive/teams/cai-internal-tools).
https://github.com/orgs/Cox-Automotive/teams/cloud-railway

2022-06-20 19:55 UTC, americk0 commented
I don't mind approving this but just be aware that by no means is the ALKS URL a sensitive or even private piece of information. I second Tommy on updating the help link to point to cloud railway though

2022-06-24 14:59 UTC, americk0 commented
This PR has been stale for a little while and we've decided not to accept this change for the reasons above. I do really appreciate the suggestion though so please feel free to submit PRs for any other issues you find. These changes may not have been accepted but it has sparked important conversations in our team

2022-06-24 14:59 UTC, closed without merging