Multi Account Provider Capability!
Cox-Automotive/terraform-provider-alks pull request #92
Opened 2020-09-15 20:25 UTC by amagana3

This is an implementation of this feature request: https://github.com/Cox-Automotive/terraform-provider-alks/issues/71. The way this works is quite simple, but basically here's an example of it in the works:

**How to use?**
```
provider "alks" {
  url = "https://alks.coxautoinc.com/rest"
}

provider "alks" {
  url     = "https://alks.coxautoinc.com/rest"
  account = "<account No>"
  role    = "<role>"
  alias   = "second"
}

# CREATE IAM ROLE -- Initial Provider
resource "alks_iamrole" "test_role" {
  name                     = "TEST-DELETE"
  type                     = "AWS CodeBuild"
  include_default_policies = false
  enable_alks_access       = true
}

# CREATE IAM ROLE -- Secondary Provider
resource "alks_iamrole" "test_role_nonprod" {
  provider                 = alks.second
  name                     = "TEST-DELETE"
  type                     = "AWS CodeBuild"
  include_default_policies = false
  enable_alks_access       = true
}
```

As long as you specify another provider with the `account`, `role`, and `alias` attributes, then you're able to generate resources for multiple accounts (THAT YOU HAVE ACCESS TO) in one `terraform apply`. This is pretty powerful stuff, and could be even extended to modules. 

**How was this implemented?**
Here's the flow as it is easier than explaining (look at code :))
1. Get credentials like normal for the initial connection - can think of this as the "main" account access.
2. If the account and role fields are set, then let's generate new STS session for the specified account/role. Note: this will verify if you have access to the account, so no tricks please.
3. Once we validate, and STS keys are generated, set the new session for the provider.
4. Done!

2020-09-15 20:27 UTC, amagana3 commented
Note to self: Still looking / researching for a way to return back the keys to the user in case they would like to make calls from the specified account.

2020-09-17 18:14 UTC, amagana3 commented
### Update
Alright this is a bit of a big update, but the latest code adds the following:
- New data source created for generating ALKS keys to a specific account which is based on the provider used.
- New data source is added to the provider definition.
- Updated docs
- Updated `example/alks.tf` - I hope this example / explanation is clear. Tried to be concise yet thorough.

### How does it work?
The data source when called will generate new keys / account information by context. That context is the provider, so if you're using just one provider it'll return keys and account information of that provider. Otherwise if you have multiple providers, you can add an alias to the provider and use `provider: my_provider.alias` field to specify which keys to generate with the data source. The data source can then be used to configure yet another provider such as AWS or ALKS.

2020-09-22 14:42 UTC, webbbarker requested changes
Still running through tests, but I've found at least one potential error.

2020-09-22 14:42 UTC, webbbarker commented on config.go
> +		newCreds, _ := client.CreateIamSession()
This line can fail, we should check for an error here and return early if we cannot generate keys.
```suggestion
		newCreds, err := client.CreateIamSession()
		if err != nil {
			return nil, err
		}
```

2020-09-23 15:17 UTC, webbbarker approved these changes
Good work.  👍

2020-10-20 13:43 UTC, merged